name = input("please enter any name you like here:")
print(name[3])#indexing
print(len(name))
print(name[2:4])
print(len(name[2:4]))
print(name[-1:-3])
print(name.upper())
print(len(name))
print(min(name))
print(max(name))
print(name.strip())
print(name.replace("o","k"))
#print(name.split(""))
print("me" in name)
print("or" not in name)
print(name.casefold())
print(name+"name")
print('i \' m a man')
print("\[\]")
print(name.capitalize())
print(name.title())
print(name.count("e"))
country = "NiGeRiA"
print(country.swapcase())
print("victor()")
victor = "trainee"
print(name.count("u"))
print("+".join(name))
print(name.strip(","))
print(name.split(","))


